name: Testing Depdendent Jobs
on:
  push:
    branches: [master]

jobs:
  mainJob:
    runs-on: ubuntu-latest
    steps:
      - name: first
        run: echo 'First job ran successfully!'
      - name: second
        run: echo $name
  slackNotification:
    needs: mainJob
    name: Slack Notification
    runs-on: ubuntu-latest
    if: always()
    steps:
      - uses: actions/checkout@v2
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: github
          SLACK_COLOR: ${{ needs.mainJob.result == 'success' && 'good' || 'danger' }}
          SLACK_ICON: https://github.com/rtCamp.png?size=48
          SLACK_MESSAGE: ${{ needs.mainJob.result == 'success' && 'Testing Depdendent Jobs - Deployment was successful!' || 'Testing Depdendent Jobs - Deployment has failed!' }}
          SLACK_TITLE: ${{ needs.mainJob.result == 'success' && 'Deployment successful :white_check_mark:' || 'Deployment failed :negative_squared_cross_mark:' }}
          SLACK_USERNAME: rtBot
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
